### ISSUE TITLE
是还在开发中么，为什么bar没有显示？

### ISSUE THREAD

**Issue by yswf** [waterbeside/oh-my-gantt#1]
我看见开发文档还比较完整，试了下该库，发现并未成功显示出对应日期进度条

**Comment by waterbeside** [comment]
> 我看见开发文档还比较完整，试了下该库，发现并未成功显示出对应日期进度条

Hi, yswf，十分感谢您返馈的问题。你所述的问题的确存在于`v1.2.5`和`v1.2.6`两个版本中，现在已经修复，可更新到**最新版本**，或退回到`v1.2.4`。谢谢！
